-- =====================================================================
-- SCHEMA ORIGINAL (nomes e estrutura preservados) + SEGURANÇA + LGPD
-- Marcadores:  [SEG] = segurança   [LGPD] = privacidade / direitos do titular
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------
-- TABELAS ORIGINAIS
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    -- [SEG] só aceita hashes bcrypt ($2a/$2b/$2y) ou argon2; impede senha em texto puro
    CONSTRAINT chk_users_password_hash_format
        CHECK (password_hash ~ '^\$(argon2id|argon2i|2[aby])\$')
);

CREATE TABLE transactions (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type_transaction         VARCHAR(40) NOT NULL,   -- 'cancelamento_boleto' | 'correcao_compra' | 'instalacao_app' | 'outro'
    amount                   NUMERIC(12,2),
    description_transaction  TEXT,                    -- descrição gerada pelo sistema
    description_client       TEXT,                    -- relato do próprio usuário
    channel                  VARCHAR(60),             -- 'ligacao' | 'whatsapp' | 'sms' | 'email'
    status_transaction       VARCHAR(20) NOT NULL DEFAULT 'pending',
    verification_code_hash VARCHAR(256),
    verification_code_expires_at TIMESTAMPTZ,
    verification_attempts    SMALLINT NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmed_at              TIMESTAMPTZ,

    CONSTRAINT chk_transactions_status
        CHECK (status_transaction IN ('pending', 'confirmed', 'cancelled', 'expired')),
    CONSTRAINT chk_transactions_confirmation_time
        CHECK (
            (status_transaction = 'confirmed' AND confirmed_at IS NOT NULL) OR
            (status_transaction <> 'confirmed' AND confirmed_at IS NULL)
        ),
    CONSTRAINT chk_transactions_code_expiry
        CHECK (
            (verification_code_hash IS NULL AND verification_code_expires_at IS NULL) OR
            (verification_code_hash IS NOT NULL AND verification_code_expires_at IS NOT NULL)
        ),
    CONSTRAINT chk_transactions_attempts
        CHECK (verification_attempts BETWEEN 0 AND 5),
    CONSTRAINT chk_transactions_type
        CHECK (type_transaction IN ('cancelamento_boleto', 'correcao_compra', 'instalacao_app', 'outro')),
    CONSTRAINT chk_transactions_amount
        CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT chk_transactions_channel
        CHECK (channel IS NULL OR channel IN ('ligacao', 'whatsapp', 'sms', 'email')),

    -- [SEG] o hash do código deve ser HMAC-SHA256 em hex (64 caracteres), nunca o código em claro
    CONSTRAINT chk_transactions_code_hash_format
        CHECK (verification_code_hash IS NULL OR verification_code_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_transactions_user_recent
    ON transactions (user_id, created_at DESC);

CREATE INDEX idx_transactions_pending_recent
    ON transactions (created_at DESC)
    WHERE status_transaction = 'pending';

CREATE TABLE scam_patterns (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category    VARCHAR(80)  NOT NULL UNIQUE,
    title       VARCHAR(150) NOT NULL,
    description TEXT         NOT NULL,
    keywords    TEXT[]       NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE alerts (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    transaction_id     UUID REFERENCES transactions(id),
    pattern_id         BIGINT REFERENCES scam_patterns(id),

    contact_channel    VARCHAR(20) NOT NULL,   -- 'ligacao' | 'whatsapp' | 'sms' | 'email'
    origin_number      VARCHAR(20) NOT NULL,
    description_alert  TEXT NOT NULL,

    scam_category      VARCHAR(80),            -- preenchido pela IA com base no padrão de golpe detectado
    risk_level         VARCHAR(10),            -- 'low' | 'medium' | 'high'
    risk_score         NUMERIC(5,2),           -- 0.00 a 100.00
    ai_justification   TEXT,
    ai_flags           JSONB NOT NULL DEFAULT '[]',
    status_ia          VARCHAR(20) NOT NULL DEFAULT 'pending',

    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_alerts_risk_level
        CHECK (risk_level IN ('low', 'medium', 'high') OR risk_level IS NULL),
    CONSTRAINT chk_alerts_status_ia
        CHECK (status_ia IN ('pending', 'evaluated', 'evaluation_failure')),
    CONSTRAINT chk_alerts_score_range
        CHECK (risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)),
    CONSTRAINT chk_alerts_contact_channel
        CHECK (contact_channel in ('ligacao', 'whatsapp', 'sms', 'email'))
);

CREATE INDEX idx_alerts_user_recent
    ON alerts (user_id, created_at DESC);
CREATE INDEX idx_alerts_category ON alerts (scam_category);
CREATE INDEX idx_alerts_risk_recent
    ON alerts (risk_level, created_at DESC)
    WHERE risk_level IS NOT NULL;
CREATE INDEX idx_alerts_ai_flags ON alerts USING GIN (ai_flags); -- o comando gin permite busca dentro do array JSON
CREATE INDEX idx_alerts_transaction_id
    ON alerts (transaction_id)
    WHERE transaction_id IS NOT NULL;
CREATE INDEX idx_scam_patterns_keywords
    ON scam_patterns USING GIN (keywords);
CREATE INDEX idx_alerts_pattern_id
    ON alerts (pattern_id)
    WHERE pattern_id IS NOT NULL;

-- Trigger que mantém users.updated_at
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION trg_set_updated_at();

INSERT INTO scam_patterns (category, title, description, keywords) VALUES
('falso_funcionario_banco',
 'Falso funcionário do banco',
 'Golpista se passa por funcionário do banco por ligação, SMS, WhatsApp ou e-mail e induz a vítima a instalar apps, clicar em links ou cancelar boletos/compras.',
 ARRAY['funcionario do banco', 'cancelar boleto', 'instalar aplicativo', 'codigo de seguranca']);


-- =====================================================================
-- NOVAS TABELAS (apenas adições; nenhuma tabela/coluna original alterada)
-- =====================================================================

-- [LGPD] Registro de consentimento / base legal por finalidade (art. 7 e 8)
CREATE TABLE consents (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    purpose        VARCHAR(80) NOT NULL,          -- ex.: 'analise_antifraude', 'contato_por_sms'
    legal_basis    VARCHAR(30) NOT NULL,
    policy_version VARCHAR(20) NOT NULL,          -- versão da política de privacidade aceita
    granted_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at     TIMESTAMPTZ,

    CONSTRAINT chk_consents_legal_basis
        CHECK (legal_basis IN ('consentimento', 'obrigacao_legal', 'execucao_contrato',
                               'legitimo_interesse', 'prevencao_fraude', 'exercicio_direitos')),
    CONSTRAINT chk_consents_revocation
        CHECK (revoked_at IS NULL OR revoked_at >= granted_at)
);
CREATE INDEX idx_consents_user_id ON consents (user_id);

-- [LGPD] Solicitações do titular (art. 18). Prazo padrão de 15 dias (art. 19, II)
CREATE TABLE privacy_requests (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    request_type  VARCHAR(30) NOT NULL,
    status        VARCHAR(15) NOT NULL DEFAULT 'open',
    requested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_at        TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '15 days'),
    completed_at  TIMESTAMPTZ,
    notes         TEXT,

    CONSTRAINT chk_privacy_requests_type
        CHECK (request_type IN ('acesso', 'correcao', 'anonimizacao', 'eliminacao',
                                'portabilidade', 'revogacao_consentimento', 'informacao')),
    CONSTRAINT chk_privacy_requests_status
        CHECK (status IN ('open', 'in_progress', 'completed', 'rejected')),
    CONSTRAINT chk_privacy_requests_completion
        CHECK ((status IN ('completed', 'rejected')) = (completed_at IS NOT NULL))
);
CREATE INDEX idx_privacy_requests_user_id ON privacy_requests (user_id);
CREATE INDEX idx_privacy_requests_open ON privacy_requests (due_at)
    WHERE status IN ('open', 'in_progress');

-- [SEG][LGPD] Trilha de auditoria. Guarda SÓ nomes de colunas alteradas, nunca valores pessoais
CREATE TABLE audit_log (
    id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    occurred_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor            TEXT NOT NULL,
    action           VARCHAR(20) NOT NULL,
    table_name       VARCHAR(63) NOT NULL,
    record_id        TEXT,
    changed_columns  TEXT[],
    purpose          TEXT,

    CONSTRAINT chk_audit_log_action
        CHECK (action IN ('INSERT', 'UPDATE', 'DELETE', 'READ', 'EXPORT', 'ANONYMIZE'))
);
CREATE INDEX idx_audit_log_table_record ON audit_log (table_name, record_id);
CREATE INDEX idx_audit_log_occurred_at  ON audit_log (occurred_at);


-- =====================================================================
-- [SEG][LGPD] AUDITORIA AUTOMÁTICA
-- actor records the authenticated PostgreSQL login (session_user).
-- With a shared application login, it does not identify the end user.
-- =====================================================================
CREATE OR REPLACE FUNCTION trg_audit_row()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
    v_changed TEXT[];
    v_id      TEXT;
BEGIN
    IF TG_OP = 'INSERT' THEN
        v_id := to_jsonb(NEW)->>'id';
    ELSIF TG_OP = 'DELETE' THEN
        v_id := to_jsonb(OLD)->>'id';
    ELSE
        v_id := to_jsonb(NEW)->>'id';
        SELECT array_agg(n.key ORDER BY n.key) INTO v_changed
        FROM jsonb_each(to_jsonb(NEW)) n
        JOIN jsonb_each(to_jsonb(OLD)) o USING (key)
        WHERE n.value IS DISTINCT FROM o.value
          AND n.key NOT IN ('updated_at', 'verification_attempts');
        IF v_changed IS NULL THEN
            RETURN NULL;   -- só ruído (updated_at / tentativas): não registra
        END IF;
    END IF;

    INSERT INTO audit_log (actor, action, table_name, record_id, changed_columns)
    VALUES (session_user::TEXT,
            TG_OP, TG_TABLE_NAME, v_id, v_changed);
    RETURN NULL;
END;
$fn$;

CREATE TRIGGER users_audit        AFTER INSERT OR UPDATE OR DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION trg_audit_row();
CREATE TRIGGER transactions_audit AFTER INSERT OR UPDATE OR DELETE ON transactions
    FOR EACH ROW EXECUTE FUNCTION trg_audit_row();
CREATE TRIGGER alerts_audit       AFTER INSERT OR UPDATE OR DELETE ON alerts
    FOR EACH ROW EXECUTE FUNCTION trg_audit_row();
CREATE TRIGGER consents_audit AFTER INSERT OR UPDATE OR DELETE ON consents
    FOR EACH ROW EXECUTE FUNCTION trg_audit_row();
CREATE TRIGGER privacy_requests_audit AFTER INSERT OR UPDATE OR DELETE ON privacy_requests
    FOR EACH ROW EXECUTE FUNCTION trg_audit_row();

-- Leituras não disparam trigger: a aplicação chama esta função ao exibir dados pessoais
CREATE OR REPLACE FUNCTION log_access(
    p_table     TEXT,
    p_record_id TEXT,
    p_action    TEXT DEFAULT 'READ',
    p_purpose   TEXT DEFAULT NULL
) RETURNS VOID
LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
    INSERT INTO audit_log (actor, action, table_name, record_id, purpose)
    VALUES (session_user::TEXT,
            p_action, p_table, p_record_id, p_purpose);
$fn$;


-- =====================================================================
-- [SEG] VERIFICAÇÃO ATÔMICA DO CÓDIGO (anti força bruta)
-- A aplicação envia o HMAC do código; a comparação, a contagem de tentativas
-- e o bloqueio acontecem numa única operação com lock de linha.
-- =====================================================================
CREATE OR REPLACE FUNCTION verify_transaction_code(
    p_transaction_id UUID,
    p_user_id BIGINT,
    p_code_hash TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
    t transactions%ROWTYPE;
BEGIN
        SELECT * INTO t
            FROM transactions
         WHERE id = p_transaction_id AND user_id = p_user_id
         FOR UPDATE;

    IF NOT FOUND OR t.status_transaction <> 'pending' OR t.verification_code_hash IS NULL THEN
        RETURN FALSE;
    END IF;

    IF t.verification_code_expires_at < now() THEN
        UPDATE transactions
           SET status_transaction = 'expired',
               verification_code_hash = NULL,
               verification_code_expires_at = NULL
         WHERE id = t.id;
        RETURN FALSE;
    END IF;

    IF t.verification_code_hash = p_code_hash THEN
        UPDATE transactions
           SET status_transaction = 'confirmed',
               confirmed_at = now(),
               verification_code_hash = NULL,          -- minimização: descarta o hash após o uso
               verification_code_expires_at = NULL
         WHERE id = t.id;
        RETURN TRUE;
    END IF;

    IF t.verification_attempts + 1 >= 5 THEN
        UPDATE transactions
           SET verification_attempts = 5,
               status_transaction = 'cancelled',       -- 5 erros: bloqueia a transação
               verification_code_hash = NULL,
               verification_code_expires_at = NULL
         WHERE id = t.id;
    ELSE
        UPDATE transactions
           SET verification_attempts = verification_attempts + 1
         WHERE id = t.id;
    END IF;
    RETURN FALSE;
END;
$fn$;

-- [SEG][LGPD] Job periódico: expira códigos vencidos e descarta o hash (minimização)
CREATE OR REPLACE FUNCTION expire_pending_transactions()
RETURNS INTEGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
    v_count INTEGER;
BEGIN
    UPDATE transactions
       SET status_transaction = 'expired',
           verification_code_hash = NULL,
           verification_code_expires_at = NULL
     WHERE status_transaction = 'pending'
       AND verification_code_expires_at < now();
    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN v_count;
END;
$fn$;


-- =====================================================================
-- [LGPD] DIREITOS DO TITULAR
-- =====================================================================

-- Eliminação/anonimização (art. 18, IV e VI). Usa anonimização em vez de DELETE porque
-- alerts.user_id é RESTRICT e os alertas têm valor para prevenção a fraudes.
-- Mantém: origin_number (número do golpista, tratado para prevenção a fraudes - art. 7º, IX
-- e art. 11, II, g), tipo, valor, canal, categoria e score.
CREATE OR REPLACE FUNCTION anonymize_user(
    p_user_id BIGINT,
    p_bcrypt_hash TEXT,
    p_request_id UUID DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
BEGIN
    IF p_bcrypt_hash IS NULL OR p_bcrypt_hash !~ '^\$2[aby]\$' THEN
        RAISE EXCEPTION 'A BCrypt hash for a random discarded secret is required';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM users
                    WHERE id = p_user_id AND email NOT LIKE '%@anonimizado.invalid') THEN
        RETURN FALSE;   -- inexistente ou já anonimizado
    END IF;

    UPDATE users
       SET username      = 'anon_' || id,
           email         = 'anon_' || id || '@anonimizado.invalid',
           phone         = NULL,
           password_hash = p_bcrypt_hash,
           active        = FALSE
     WHERE id = p_user_id;

    UPDATE transactions
       SET description_client           = NULL,
           description_transaction      = NULL,
           verification_code_hash       = NULL,
           verification_code_expires_at = NULL,
           status_transaction = CASE WHEN status_transaction = 'pending'
                                     THEN 'cancelled' ELSE status_transaction END
     WHERE user_id = p_user_id;

    UPDATE alerts
       SET description_alert = '[removido a pedido do titular]',
           ai_justification  = NULL
     WHERE user_id = p_user_id;

    UPDATE consents SET revoked_at = now()
     WHERE user_id = p_user_id AND revoked_at IS NULL;

    IF p_request_id IS NOT NULL THEN
        UPDATE privacy_requests
           SET status = 'completed', completed_at = now()
         WHERE id = p_request_id AND user_id = p_user_id;
    END IF;

    INSERT INTO audit_log (actor, action, table_name, record_id, purpose)
    VALUES (session_user::TEXT,
            'ANONYMIZE', 'users', p_user_id::TEXT,
            COALESCE('privacy_request ' || p_request_id::TEXT, 'sem solicitação vinculada'));
    RETURN TRUE;
END;
$fn$;

-- Acesso e portabilidade (art. 18, II e V). Nunca inclui hashes de senha/código
CREATE OR REPLACE FUNCTION export_user_data(p_user_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
DECLARE
    v_result JSONB;
BEGIN
    SELECT jsonb_build_object(
        'user', (SELECT to_jsonb(u) - 'password_hash' FROM users u WHERE u.id = p_user_id),
        'transactions', COALESCE((SELECT jsonb_agg(to_jsonb(t)
                                   - 'verification_code_hash'
                                   - 'verification_code_expires_at'
                                   - 'verification_attempts')
                                  FROM transactions t WHERE t.user_id = p_user_id), '[]'::jsonb),
        'alerts', COALESCE((SELECT jsonb_agg(to_jsonb(a))
                              FROM alerts a WHERE a.user_id = p_user_id), '[]'::jsonb),
        'consents', COALESCE((SELECT jsonb_agg(to_jsonb(c))
                                FROM consents c WHERE c.user_id = p_user_id), '[]'::jsonb)
    ) INTO v_result;

    INSERT INTO audit_log (actor, action, table_name, record_id, purpose)
    VALUES (session_user::TEXT,
            'EXPORT', 'users', p_user_id::TEXT, 'portabilidade/acesso do titular');
    RETURN v_result;
END;
$fn$;


-- =====================================================================
-- [SEG] MENOR PRIVILÉGIO
-- Papéis NOLOGIN: crie os logins reais e faça GRANT app_rw TO seu_login;
-- =====================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
        CREATE ROLE app_rw NOLOGIN;           -- backend da aplicação
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_ro') THEN
        CREATE ROLE app_ro NOLOGIN;           -- painel / relatórios (somente leitura)
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'privacy_officer') THEN
        CREATE ROLE privacy_officer NOLOGIN;  -- encarregado de dados (DPO)
    END IF;
END
$$;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO app_rw, app_ro, privacy_officer;

-- Funções sensíveis: tira o EXECUTE padrão de PUBLIC e libera só a quem precisa
REVOKE ALL ON FUNCTION verify_transaction_code(UUID, BIGINT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION expire_pending_transactions()         FROM PUBLIC;
REVOKE ALL ON FUNCTION log_access(TEXT, TEXT, TEXT, TEXT)    FROM PUBLIC;
REVOKE ALL ON FUNCTION anonymize_user(BIGINT, TEXT, UUID)     FROM PUBLIC;
REVOKE ALL ON FUNCTION export_user_data(BIGINT)              FROM PUBLIC;

GRANT EXECUTE ON FUNCTION verify_transaction_code(UUID, BIGINT, TEXT) TO app_rw;
GRANT EXECUTE ON FUNCTION expire_pending_transactions()        TO app_rw;
GRANT EXECUTE ON FUNCTION log_access(TEXT, TEXT, TEXT, TEXT)   TO app_rw, app_ro, privacy_officer;
GRANT EXECUTE ON FUNCTION anonymize_user(BIGINT, TEXT, UUID)    TO privacy_officer;
GRANT EXECUTE ON FUNCTION export_user_data(BIGINT)             TO privacy_officer;

-- app_rw: sem DELETE em nenhuma tabela (eliminação = anonymize_user)
GRANT SELECT, INSERT, UPDATE ON users TO app_rw;

-- transactions: o app não lê o hash, não define status/confirmação/tentativas diretamente.
-- Confirmar só é possível via verify_transaction_code().
GRANT SELECT (id, user_id, type_transaction, amount, description_transaction, description_client,
              channel, status_transaction, verification_code_expires_at, verification_attempts,
              created_at, confirmed_at)
    ON transactions TO app_rw;
GRANT INSERT (id, user_id, type_transaction, amount, description_transaction, description_client,
              channel, verification_code_hash, verification_code_expires_at)
    ON transactions TO app_rw;
GRANT UPDATE (type_transaction, amount, description_transaction, description_client, channel,
              verification_code_hash, verification_code_expires_at)
    ON transactions TO app_rw;

GRANT SELECT, INSERT, UPDATE ON alerts TO app_rw;
GRANT SELECT ON scam_patterns TO app_rw, app_ro;
GRANT SELECT, INSERT ON consents TO app_rw;
GRANT UPDATE (revoked_at) ON consents TO app_rw;
GRANT SELECT, INSERT ON privacy_requests TO app_rw;

-- app_ro: leitura sem colunas secretas
GRANT SELECT (id, username, email, phone, created_at, updated_at, active) ON users TO app_ro;
GRANT SELECT (id, user_id, type_transaction, amount, description_transaction, description_client,
              channel, status_transaction, verification_attempts, created_at, confirmed_at)
    ON transactions TO app_ro;
GRANT SELECT ON alerts, consents TO app_ro;

-- Encarregado de dados
GRANT SELECT ON privacy_requests, consents, audit_log TO privacy_officer;
GRANT UPDATE (status, completed_at, notes) ON privacy_requests TO privacy_officer;

-- audit_log: ninguém (além do dono) escreve ou apaga direto; só as funções SECURITY DEFINER


-- =====================================================================
-- [LGPD] CLASSIFICAÇÃO DOS DADOS (documentação no próprio catálogo)
-- =====================================================================
COMMENT ON COLUMN users.username                IS 'LGPD: dado pessoal (identificador)';
COMMENT ON COLUMN users.email                   IS 'LGPD: dado pessoal (contato)';
COMMENT ON COLUMN users.phone                   IS 'LGPD: dado pessoal (contato)';
COMMENT ON COLUMN users.password_hash           IS 'SEGURANÇA: credencial; nunca expor, logar ou exportar';
COMMENT ON COLUMN transactions.description_client IS 'LGPD: texto livre do titular; pode conter dados pessoais; limpo na anonimização';
COMMENT ON COLUMN transactions.verification_code_hash IS 'SEGURANÇA: HMAC-SHA256 hex com pepper fora do banco; descartado após uso/expiração';
COMMENT ON COLUMN alerts.origin_number          IS 'LGPD: contato de terceiro (suspeito de fraude); base legal: prevenção a fraudes (art. 7º IX / 11 II g)';
COMMENT ON COLUMN alerts.description_alert      IS 'LGPD: texto livre; limpo na anonimização do titular';
COMMENT ON TABLE  audit_log                     IS 'Trilha de auditoria: apenas nomes de colunas, nunca valores pessoais';